from .node import NODE_CLASS_MAPPINGS as _T, NODE_DISPLAY_NAME_MAPPINGS as _TN
from .node_image_gen import NODE_CLASS_MAPPINGS as _I, NODE_DISPLAY_NAME_MAPPINGS as _IN
from .node_audio import NODE_CLASS_MAPPINGS as _A, NODE_DISPLAY_NAME_MAPPINGS as _AN

NODE_CLASS_MAPPINGS = {**_T, **_I, **_A}
NODE_DISPLAY_NAME_MAPPINGS = {**_TN, **_IN, **_AN}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
